# Site settings
title: Bristol SEDS Pico Tracker
email:
description:
  Microsite for the Bristol SEDS Pico Tracker
baseurl: "/pico-tracker" # the subpath of your site, e.g. /blog/
url: "http://www.bristol-seds.co.uk" # the base hostname & protocol for your site
twitter_username:
github_username: bristol-seds
flickr_username: bristolseds
facebook_group: "Bristol SEDS"

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->
